### ISSUE TITLE
Crash when no menu with manual instanciation

### ISSUE THREAD

**Issue by FredJul** [lurbas/ListItemView#1]
If you instanciate manually the view with a Context and without attributes, the construction will crash when trying to inflate the menu (which is initialized to a invalid 0 value).

I would be able to set it after the constructor.

**Comment by lurbas** [comment]
Hi FredJul,
thanks for reporting the issue. Will fix asap.

**Comment by passsy** [comment]
`private int mMenuId = -1;` would fix this

**Comment by mradzinski** [comment]
Yep, to expand a bit on @passsy comment, [Here](https://github.com/lurbas/ListItemView/blob/master/listitemview/src/main/java/com/lucasurbas/listitemview/ListItemView.java#L100) is the issue.

**Comment by lurbas** [comment]
Sorry for late response. Issue fixed with 1.0.1 release. cheers
