### ISSUE TITLE
how to access that color picker, independent of other views?

### ISSUE THREAD

**Issue by jitendrapurohit12** [lurbas/ListItemView#11]
I want to that color picker to set color of some views of my app. this color picker looks a perfect color picker i have ever seen.can you please tell how can i use that?

**Comment by passsy** [comment]
The sample uses this library as color picker. https://github.com/jrummyapps/colorpicker

`compile 'com.jrummyapps:colorpicker:2.1.6'`

**Comment by lurbas** [comment]
Closing
