### ISSUE TITLE
Use with adapter and viewholder 

### ISSUE THREAD

**Issue by ludiaz** [lurbas/ListItemView#16]
Hello,

How can i use setOnMenuItemClickListener when my listview use a adapter (extends BaseAdapter)?

My adapter have a ViewHolder with the ListItemView. When i inflate 

The problem is get the number of the line of used menu, for example, i have item delete for all lines, want delete one, and i don't know the right way to do this.

Thanks for the project, it's amazing. And, sorry for my bad english.

**Comment by lurbas** [comment]
Hey, this is not really a question for the library, but how to handle clicks in recyclerview adapter. Basically, you can create your own listener and pass it through. You will find a lot of examples on Stackoverflow eg https://stackoverflow.com/questions/24885223/why-doesnt-recyclerview-have-onitemclicklistener
